version: '3'
services: 
    db:
        image: postgres:latest
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always

    backend:
        build: ./backend
        ports: 
            - "8000:8000"
        container_name: backend_django
        volumes: 
            - ./data/backend:/usr/src/django
        depends_on:
            - db
        restart: always

    frontend:
        build: ./frontend
        ports: 
            - "3000:3000"
        container_name: frontend_reactjs
        volumes: 
            - ./data/frontend:/usr/src/reactjs
        depends_on: 
            - backend
        restart: always

