# Generated by Django 3.2.5 on 2021-08-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fashion',
            old_name='colors',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='fashion',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
