# Generated by Django 3.2.5 on 2021-08-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20210819_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion',
            name='size',
        ),
        migrations.CreateModel(
            name='FashionDetail',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='chatbot.fashion')),
                ('size', models.CharField(max_length=3)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fashiondetail',
                'unique_together': {('id', 'size')},
            },
        ),
    ]
