# Generated by Django 3.2.5 on 2021-08-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20210824_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='material',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
